// ==========================================================
// Coding Hub starter content - JavaScript.
// ==========================================================

export default {
  subject: 'javascript',

  lessons: [
    {
      topic: 'Variables',
      title: 'Variables: let, const and the one you should not use',
      summary: 'Store values with the right keyword, and understand what block scope actually protects you from.',
      minutes: 14,
      objectives: [
        'Declare variables with let and const',
        'Explain why var is avoided in new code',
        'Describe block scope',
        'Predict what happens when a const object is modified'
      ],
      blocks: [
        { type: 'paragraph', text: 'A variable is a name for a value. JavaScript gives you three keywords to create one, and in modern code you only need two of them.' },
        { type: 'code', language: 'javascript', code: 'const name = "Alex";   // cannot be reassigned\nlet score = 0;         // can be reassigned\nvar old = true;        // the old way — avoid in new code' },
        { type: 'heading', text: 'const by default, let when you must' },
        { type: 'paragraph', text: 'Start every variable as const. If you later find you genuinely need to reassign it, change it to let. This makes reassignment visible, which makes bugs easier to spot.' },
        { type: 'code', language: 'javascript', code: 'const total = 10;\ntotal = 20;   // TypeError: Assignment to constant variable.\n\nlet count = 0;\ncount = count + 1;   // fine' },
        { type: 'warning', title: 'const does not mean frozen', text: 'const stops the *name* from pointing at something else. The value itself can still change if it is an object or an array.' },
        { type: 'code', language: 'javascript', code: 'const scores = [1, 2, 3];\nscores.push(4);      // allowed — same array, new contents\nconsole.log(scores); // [1, 2, 3, 4]\n\nscores = [9];        // TypeError — this points the name somewhere new' },
        { type: 'heading', text: 'Block scope' },
        { type: 'paragraph', text: 'let and const only exist inside the nearest pair of curly braces. var ignores blocks and leaks out to the whole function, which is exactly the problem it causes.' },
        { type: 'code', language: 'javascript', code: 'if (true) {\n  let inside = "block";\n  var leaks  = "function";\n}\n\nconsole.log(leaks);   // "function"\nconsole.log(inside);  // ReferenceError: inside is not defined' },
        { type: 'heading', text: 'Naming' },
        { type: 'list', items: [
          'camelCase for normal variables: userScore, isReady, totalPrice.',
          'Names say what the value *is*: userCount, not x or data2.',
          'Booleans read like a question: isVisible, hasPermission, canEdit.',
          'A name may not start with a digit, and is case-sensitive: score and Score are different.'
        ] },
        { type: 'heading', text: 'Common mistakes' },
        { type: 'list', items: [
          'Reassigning a const and being surprised by the error.',
          'Assuming const makes an array immutable.',
          'Declaring the same let twice in one block — that is a SyntaxError.',
          'Using a let or const before the line that declares it (the "temporal dead zone").'
        ] },
        { type: 'heading', text: 'Summary' },
        { type: 'list', items: [
          'const by default, let when the value must change, var basically never.',
          'let and const are limited to their block; var is not.',
          'const protects the binding, not the contents.'
        ] }
      ],
      challenge: {
        title: 'Fix the leaky counter',
        description: 'The code below prints the wrong thing. Rewrite it using the right keywords so the totals are correct and nothing leaks out of its block.',
        requirements: [
          'No var anywhere',
          'Values that never change are const',
          'Accessing the loop variable after the loop must be a ReferenceError',
          'The final total printed is 6'
        ],
        starterCode: 'var numbers = [1, 2, 3];\nvar total = 0;\nfor (var i = 0; i < numbers.length; i++) {\n  var current = numbers[i];\n  total = total + current;\n}\nconsole.log(total);\nconsole.log(i);       // this should NOT work',
        expectedResult: 'The console prints 6, and the attempt to read the loop variable afterwards throws a ReferenceError.',
        hints: [
          'numbers never gets reassigned.',
          'total does get reassigned, so it needs the other keyword.'
        ],
        difficulty: 'beginner',
        points: 25
      }
    },

    {
      topic: 'Functions',
      title: 'Functions: naming a piece of work',
      summary: 'Declarations, expressions and arrow functions — plus parameters, return values and defaults.',
      minutes: 16,
      objectives: [
        'Write a function three different ways',
        'Pass arguments and use default parameters',
        'Explain the difference between returning and printing',
        'Choose between an arrow function and a declaration'
      ],
      blocks: [
        { type: 'paragraph', text: 'A function packages up a job so you can run it whenever you like, with different inputs, without writing the steps again.' },
        { type: 'heading', text: 'Three ways to write one' },
        { type: 'code', language: 'javascript', code: '// 1. Function declaration — hoisted, can be called before it is defined\nfunction add(a, b) {\n  return a + b;\n}\n\n// 2. Function expression — stored in a variable\nconst subtract = function (a, b) {\n  return a - b;\n};\n\n// 3. Arrow function — shortest, and the usual choice for small helpers\nconst multiply = (a, b) => a * b;' },
        { type: 'paragraph', text: 'An arrow function with a single expression returns it automatically — there is no return keyword and no braces. Add braces and you must write return yourself.' },
        { type: 'code', language: 'javascript', code: 'const double = n => n * 2;          // implicit return\n\nconst describe = n => {            // braces, so an explicit return is needed\n  const label = n > 0 ? "positive" : "not positive";\n  return label;\n};' },
        { type: 'heading', text: 'Parameters and arguments' },
        { type: 'paragraph', text: 'Parameters are the names in the definition. Arguments are the real values you pass in.' },
        { type: 'code', language: 'javascript', code: 'function greet(name, greeting = "Hello") {   // default parameter\n  return `${greeting}, ${name}!`;\n}\n\ngreet("Sam");             // "Hello, Sam!"\ngreet("Sam", "Welcome");  // "Welcome, Sam!"\ngreet();                  // "Hello, undefined!"' },
        { type: 'heading', text: 'return vs console.log' },
        { type: 'warning', title: 'This trips up almost everybody once', text: 'console.log shows a value to a human. return hands a value back to the code that called the function. A function without return gives back undefined, no matter how much it printed.' },
        { type: 'code', language: 'javascript', code: 'function badAdd(a, b) {\n  console.log(a + b);   // prints, returns nothing\n}\nconst result = badAdd(2, 3);   // prints 5\nconsole.log(result);           // undefined\n\nfunction goodAdd(a, b) {\n  return a + b;\n}\nconsole.log(goodAdd(2, 3) * 10);  // 50' },
        { type: 'paragraph', text: 'Also remember that return ends the function immediately — any code after it never runs.' },
        { type: 'heading', text: 'Best practice' },
        { type: 'list', items: [
          'One function, one job. If you need "and" to describe it, split it in two.',
          'Name it with a verb: calculateTotal, isValid, formatDate.',
          'Keep the parameter list short. More than three usually means an options object is better.',
          'Return a value rather than changing something outside the function where you can.'
        ] },
        { type: 'heading', text: 'Summary' },
        { type: 'list', items: [
          'Declarations are hoisted; expressions and arrows are not.',
          'An arrow with no braces returns its expression automatically.',
          'Default parameters fill in missing arguments.',
          'return gives a value back; console.log only displays one.'
        ] }
      ],
      challenge: {
        title: 'Write a grade calculator',
        description: 'Write a function that turns a percentage into a grade, and one that averages a list of marks.',
        requirements: [
          'gradeFor(percent) returns "A" for 80+, "B" for 70+, "C" for 60+, "D" for 50+, otherwise "F"',
          'average(marks) returns the mean of an array of numbers',
          'average([]) returns 0 rather than NaN',
          'Both functions return their value — neither prints anything'
        ],
        starterCode: 'function gradeFor(percent) {\n  // your code here\n}\n\nconst average = (marks) => {\n  // your code here\n};\n\nconsole.log(gradeFor(average([72, 85, 64])));  // should print "B"\nconsole.log(average([]));                       // should print 0',
        expectedResult: 'The first log prints "B" (the average is 73.67) and the second prints 0.',
        hints: [
          'Check the highest boundary first, then work downwards.',
          'Guard the empty array before dividing by marks.length.'
        ],
        difficulty: 'intermediate',
        points: 35
      }
    },

    {
      topic: 'Array Methods',
      title: 'map, filter and reduce',
      summary: 'Transform, select and summarise arrays without writing a single loop.',
      minutes: 16,
      objectives: [
        'Use map to transform every item',
        'Use filter to keep the items you want',
        'Use reduce to collapse an array to one value',
        'Chain the three together'
      ],
      blocks: [
        { type: 'paragraph', text: 'These three methods cover most of what people used to write for-loops for. Each one takes a function and calls it once per item. None of them changes the original array.' },
        { type: 'heading', text: 'map — same length, new values' },
        { type: 'code', language: 'javascript', code: 'const prices  = [10, 20, 30];\nconst withTax = prices.map(price => price * 1.2);\n\nconsole.log(withTax);  // [12, 24, 36]\nconsole.log(prices);   // [10, 20, 30] — untouched' },
        { type: 'heading', text: 'filter — same values, fewer of them' },
        { type: 'code', language: 'javascript', code: 'const scores = [45, 82, 67, 91, 38];\nconst passes = scores.filter(score => score >= 50);\n\nconsole.log(passes);  // [82, 67, 91]' },
        { type: 'paragraph', text: 'The function you pass to filter must return true or false. Anything truthy keeps the item; anything falsy drops it.' },
        { type: 'heading', text: 'reduce — many values, one result' },
        { type: 'code', language: 'javascript', code: 'const numbers = [1, 2, 3, 4];\n\nconst total = numbers.reduce((running, current) => running + current, 0);\nconsole.log(total);  // 10' },
        { type: 'paragraph', text: 'reduce takes two arguments: a function and a starting value. The function receives the running result and the current item, and whatever it returns becomes the running result for the next item.' },
        { type: 'note', title: 'Always pass the starting value', text: 'Without it, reduce uses the first item as the start — and throws a TypeError on an empty array. Passing 0, "" or {} explicitly avoids both surprises.' },
        { type: 'heading', text: 'Chaining' },
        { type: 'code', language: 'javascript', code: 'const students = [\n  { name: "Ada",  score: 91 },\n  { name: "Alan", score: 47 },\n  { name: "Grace", score: 88 }\n];\n\nconst averageOfPasses = students\n  .filter(s => s.score >= 50)\n  .map(s => s.score)\n  .reduce((sum, score, _i, list) => sum + score / list.length, 0);\n\nconsole.log(Math.round(averageOfPasses));  // 90' },
        { type: 'heading', text: 'The rest of the family' },
        { type: 'table', headers: ['Method', 'Gives you back'], rows: [
          ['find', 'The first matching item, or undefined'],
          ['findIndex', 'The position of the first match, or -1'],
          ['some', 'true if at least one item matches'],
          ['every', 'true if all of them match'],
          ['includes', 'true if the value is present'],
          ['forEach', 'Nothing — used only for side effects']
        ] },
        { type: 'heading', text: 'Common mistakes' },
        { type: 'list', items: [
          'Forgetting to return from the callback — map then fills the new array with undefined.',
          'Using map when nothing is being transformed. If you ignore the result, use forEach.',
          'Expecting filter to change the original array. It returns a new one; you must store it.',
          'Leaving out reduce’s initial value.'
        ] },
        { type: 'heading', text: 'Summary' },
        { type: 'list', items: [
          'map transforms, filter selects, reduce summarises.',
          'All three return something new and leave the original alone.',
          'They chain, which reads far better than nested loops.'
        ] }
      ],
      challenge: {
        title: 'Report card in one chain',
        description: 'From a list of students, produce the names of everyone who passed, in capitals, plus the class average.',
        requirements: [
          'passNames is an array of the names of students scoring 50 or more, uppercased',
          'classAverage is the mean score of *all* students, rounded to the nearest whole number',
          'No for or while loop appears anywhere',
          'The original students array is not modified'
        ],
        starterCode: 'const students = [\n  { name: "Ada",   score: 91 },\n  { name: "Alan",  score: 47 },\n  { name: "Grace", score: 88 },\n  { name: "Linus", score: 52 }\n];\n\nconst passNames = /* your code */;\nconst classAverage = /* your code */;\n\nconsole.log(passNames);     // ["ADA", "GRACE", "LINUS"]\nconsole.log(classAverage);  // 70',
        expectedResult: 'The first log prints the three uppercased names, the second prints 70.',
        hints: [
          'filter first, then map — the order matters for readability.',
          'For the average, reduce the scores then divide by students.length.'
        ],
        difficulty: 'intermediate',
        points: 35
      }
    },

    {
      topic: 'DOM',
      title: 'The DOM: making a page react',
      summary: 'Find elements, change them, create new ones and respond to what the visitor does.',
      minutes: 18,
      objectives: [
        'Select elements with querySelector and querySelectorAll',
        'Change text, HTML, classes and attributes safely',
        'Create and insert new elements',
        'Attach event listeners, including one for a whole list'
      ],
      blocks: [
        { type: 'paragraph', text: 'When a browser loads your HTML it builds the DOM — a live tree of objects representing every element. Changing the DOM changes the page immediately.' },
        { type: 'heading', text: 'Finding elements' },
        { type: 'code', language: 'javascript', code: 'const title  = document.querySelector("h1");        // the first match\nconst byId   = document.querySelector("#total");    // by id\nconst cards  = document.querySelectorAll(".card");  // all matches (a NodeList)\n\ncards.forEach(card => card.classList.add("ready"));' },
        { type: 'paragraph', text: 'querySelector takes any CSS selector you already know. querySelectorAll returns a NodeList, which has forEach but not map — spread it into an array with [...cards] if you need the full set of array methods.' },
        { type: 'heading', text: 'Changing what is there' },
        { type: 'code', language: 'javascript', code: 'title.textContent = "New heading";        // safe: treated as plain text\ntitle.classList.add("highlight");\ntitle.classList.toggle("open");\ntitle.setAttribute("data-state", "done");\ntitle.style.color = "crimson";            // prefer adding a class' },
        { type: 'warning', title: 'textContent, not innerHTML', text: 'innerHTML parses its input as markup. Putting anything a user typed into innerHTML lets them inject HTML and scripts into your page. Use textContent unless you are deliberately inserting markup you built yourself.' },
        { type: 'heading', text: 'Creating elements' },
        { type: 'code', language: 'javascript', code: 'const item = document.createElement("li");\nitem.textContent = "A new task";\nitem.classList.add("task");\n\ndocument.querySelector("#tasks").append(item);' },
        { type: 'heading', text: 'Reacting to events' },
        { type: 'code', language: 'javascript', code: 'const button = document.querySelector("#save");\n\nbutton.addEventListener("click", (event) => {\n  event.preventDefault();\n  console.log("Saved!");\n});' },
        { type: 'paragraph', text: 'The listener receives an event object. event.target is the element that was actually clicked, and preventDefault() stops the browser’s built-in behaviour — most often a form submitting and reloading the page.' },
        { type: 'heading', text: 'One listener for a whole list' },
        { type: 'paragraph', text: 'Attaching a listener to every row is slow, and breaks for rows added later. Listen on the container instead and check what was clicked — this is called event delegation.' },
        { type: 'code', language: 'javascript', code: 'document.querySelector("#tasks").addEventListener("click", (event) => {\n  const deleteButton = event.target.closest(".delete");\n  if (!deleteButton) return;\n  deleteButton.closest("li").remove();\n});' },
        { type: 'heading', text: 'Common mistakes' },
        { type: 'list', items: [
          'Running the script before the elements exist — put the <script> at the end of the body, or add defer.',
          'Writing addEventListener("click", handleClick()) with parentheses, which calls the function immediately.',
          'Using innerHTML with text a user typed.',
          'Selecting ".card" but writing class="cards" in the HTML.'
        ] },
        { type: 'heading', text: 'Summary' },
        { type: 'list', items: [
          'querySelector / querySelectorAll find elements with CSS selectors.',
          'textContent for text, classList for classes, setAttribute for attributes.',
          'createElement plus append adds new content.',
          'addEventListener responds to the visitor; delegate to a parent for lists.'
        ] }
      ],
      challenge: {
        title: 'A working to-do list',
        description: 'Build a to-do list that adds items from a form and deletes them again, with no page reload.',
        requirements: [
          'Submitting the form adds the typed text as a new <li>',
          'The form does not reload the page and the input clears afterwards',
          'Empty input adds nothing',
          'Each item has a delete button that works, including for items added after page load',
          'User text is inserted with textContent, never innerHTML'
        ],
        starterCode: '<form id="add-form">\n  <input id="task-input" placeholder="What needs doing?">\n  <button>Add</button>\n</form>\n<ul id="tasks"></ul>\n\n<script>\n  const form  = document.querySelector("#add-form");\n  const input = document.querySelector("#task-input");\n  const list  = document.querySelector("#tasks");\n\n  // your code here\n</script>',
        expectedResult: 'Typing a task and pressing Add appends it to the list; clicking its delete button removes it; the page never reloads.',
        hints: [
          'Listen for "submit" on the form, and call event.preventDefault() first.',
          'One delegated click listener on the <ul> handles every delete button, now and later.'
        ],
        difficulty: 'advanced',
        points: 45
      }
    }
  ],

  questions: [
    { topic: 'Variables', type: 'multiple_choice', difficulty: 'beginner', points: 10,
      prompt: 'Which keyword declares a variable that cannot be reassigned?',
      options: ['let', 'var', 'const', 'static'], answer: 2, tags: 'variables',
      explanation: 'const creates a binding that cannot be pointed at a different value.' },
    { topic: 'Variables', type: 'output', difficulty: 'intermediate', points: 15,
      prompt: 'What does this print?',
      code: 'const list = [1, 2];\nlist.push(3);\nconsole.log(list);',
      options: ['[1, 2]', '[1, 2, 3]', 'TypeError', 'undefined'], answer: 1, tags: 'variables',
      explanation: 'const stops reassignment of the name, not changes to the array it points at.' },
    { topic: 'Variables', type: 'output', difficulty: 'intermediate', points: 15,
      prompt: 'What happens on the last line?',
      code: 'if (true) {\n  let a = 1;\n  var b = 2;\n}\nconsole.log(b);\nconsole.log(a);',
      options: ['Prints 2 then 1', 'Prints 2 then throws a ReferenceError', 'Throws immediately', 'Prints undefined twice'],
      answer: 1, tags: 'scope',
      explanation: 'var leaks out of the block, let does not — so reading a afterwards is a ReferenceError.' },
    { topic: 'Data Types', type: 'multiple_choice', difficulty: 'beginner', points: 10,
      prompt: 'Which of these is NOT a JavaScript primitive type?',
      options: ['string', 'number', 'array', 'boolean'], answer: 2, tags: 'types',
      explanation: 'Arrays are objects. The primitives are string, number, boolean, null, undefined, symbol and bigint.' },
    { topic: 'Data Types', type: 'output', difficulty: 'advanced', points: 20,
      prompt: 'What does this print?',
      code: 'console.log(typeof null);',
      options: ['"null"', '"object"', '"undefined"', '"NaN"'], answer: 1, tags: 'types',
      explanation: 'A long-standing bug in the language, kept for backwards compatibility. Test for null with value === null.' },
    { topic: 'Operators', type: 'output', difficulty: 'intermediate', points: 15,
      prompt: 'What is the result?',
      code: 'console.log("5" + 3);\nconsole.log("5" - 3);',
      options: ['8 then 2', '"53" then 2', '"53" then "53"', '8 then "2"'], answer: 1, tags: 'operators',
      explanation: '+ prefers string concatenation when either side is a string; - has no string meaning, so both sides are converted to numbers.' },
    { topic: 'Operators', type: 'multiple_choice', difficulty: 'intermediate', points: 15,
      prompt: 'What is the difference between == and ===?',
      options: ['None', '=== also compares the type', '== is only for numbers', '=== is only for objects'],
      answer: 1, tags: 'operators',
      explanation: '== converts types before comparing, so "1" == 1 is true. === requires the same type, so "1" === 1 is false. Prefer ===.' },
    { topic: 'Strings', type: 'multiple_choice', difficulty: 'beginner', points: 10,
      prompt: 'Which syntax lets you insert a variable straight into a string?',
      options: ['Template literals with backticks', 'Single quotes', 'Double quotes', 'String.insert()'],
      answer: 0, tags: 'strings',
      explanation: 'Backticks allow ${expression} anywhere inside the string, and support real line breaks.' },
    { topic: 'String Methods', type: 'output', difficulty: 'intermediate', points: 15,
      prompt: 'What is logged?',
      code: 'const name = "  Ada  ";\nconsole.log(name.trim().toUpperCase());',
      options: ['"  ADA  "', '"ADA"', '"Ada"', 'undefined'], answer: 1, tags: 'strings',
      explanation: 'trim() removes whitespace at both ends, then toUpperCase() capitalises. Strings are immutable, so name itself is unchanged.' },
    { topic: 'Arrays', type: 'multiple_choice', difficulty: 'beginner', points: 10,
      prompt: 'What is the index of the first item in an array?',
      options: ['1', '0', '-1', 'It depends on the array'], answer: 1, tags: 'arrays',
      explanation: 'JavaScript arrays are zero-indexed, so the last index is always length - 1.' },
    { topic: 'Arrays', type: 'output', difficulty: 'intermediate', points: 15,
      prompt: 'What does this print?',
      code: 'const a = [1, 2, 3];\nconst b = a;\nb.push(4);\nconsole.log(a.length);',
      options: ['3', '4', '0', 'TypeError'], answer: 1, tags: 'references',
      explanation: 'Arrays are copied by reference, so a and b are the same array. Use [...a] to make a real copy.' },
    { topic: 'Objects', type: 'multiple_choice', difficulty: 'beginner', points: 10,
      prompt: 'How do you read the name property of an object called user?',
      options: ['user->name', 'user.name', 'user::name', 'user(name)'], answer: 1, tags: 'objects',
      explanation: 'Dot notation, or user["name"] when the key is held in a variable.' },
    { topic: 'Objects', type: 'output', difficulty: 'advanced', points: 20,
      prompt: 'What is logged?',
      code: 'const user = { name: "Ada", address: { city: "London" } };\nconst copy = { ...user };\ncopy.address.city = "Paris";\nconsole.log(user.address.city);',
      options: ['"London"', '"Paris"', 'undefined', 'TypeError'], answer: 1, tags: 'objects',
      explanation: 'The spread operator makes a shallow copy: nested objects are still shared. structuredClone(user) makes a deep copy.' },
    { topic: 'Functions', type: 'output', difficulty: 'beginner', points: 10,
      prompt: 'What is printed?',
      code: 'function add(a, b) {\n  console.log(a + b);\n}\nconst result = add(2, 3);\nconsole.log(result);',
      options: ['5 then 5', '5 then undefined', 'undefined then 5', '5 only'], answer: 1, tags: 'functions',
      explanation: 'The function prints 5 but returns nothing, so result is undefined. Printing is not returning.' },
    { topic: 'Functions', type: 'multiple_choice', difficulty: 'intermediate', points: 15,
      prompt: 'What does an arrow function with no braces do?',
      options: ['Nothing — it is invalid', 'Returns its expression automatically', 'Always returns undefined', 'Runs immediately'],
      answer: 1, tags: 'functions',
      explanation: 'n => n * 2 is the same as n => { return n * 2; }.' },
    { topic: 'Parameters', type: 'output', difficulty: 'intermediate', points: 15,
      prompt: 'What is logged?',
      code: 'function greet(name, greeting = "Hi") {\n  return greeting + ", " + name;\n}\nconsole.log(greet("Sam"));',
      options: ['"Hi, Sam"', '", Sam"', '"undefined, Sam"', 'TypeError'], answer: 0, tags: 'functions',
      explanation: 'The default parameter fills in when the argument is missing or undefined.' },
    { topic: 'Return Values', type: 'true_false', difficulty: 'beginner', points: 10,
      prompt: 'Code written after a return statement in the same function still runs.', answer: 'false', tags: 'functions',
      explanation: 'return exits the function immediately.' },
    { topic: 'Conditions', type: 'output', difficulty: 'intermediate', points: 15,
      prompt: 'What is logged?',
      code: 'const value = 0;\nif (value) {\n  console.log("truthy");\n} else {\n  console.log("falsy");\n}',
      options: ['"truthy"', '"falsy"', 'Nothing', 'An error'], answer: 1, tags: 'conditions',
      explanation: 'The falsy values are false, 0, -0, 0n, "", null, undefined and NaN. Everything else is truthy.' },
    { topic: 'Loops', type: 'output', difficulty: 'beginner', points: 10,
      prompt: 'How many times does this loop run?',
      code: 'for (let i = 0; i < 5; i++) {\n  console.log(i);\n}',
      options: ['4', '5', '6', 'Forever'], answer: 1, tags: 'loops',
      explanation: 'It runs for i = 0, 1, 2, 3, 4 — five times, stopping before 5.' },
    { topic: 'Loops', type: 'multiple_choice', difficulty: 'intermediate', points: 15,
      prompt: 'Which loop is best for iterating the *values* of an array?',
      options: ['for...in', 'for...of', 'while', 'do...while'], answer: 1, tags: 'loops',
      explanation: 'for...of gives values; for...in gives keys and is meant for objects.' },
    { topic: 'Array Methods', type: 'output', difficulty: 'intermediate', points: 15,
      prompt: 'What is logged?',
      code: 'const nums = [1, 2, 3, 4];\nconsole.log(nums.filter(n => n % 2 === 0));',
      options: ['[1, 3]', '[2, 4]', '[true, false]', '2'], answer: 1, tags: 'arrays',
      explanation: 'filter keeps items whose callback returns true — here the even numbers.' },
    { topic: 'Array Methods', type: 'output', difficulty: 'advanced', points: 20,
      prompt: 'What is logged?',
      code: 'const nums = [1, 2, 3];\nconsole.log(nums.map(n => { n * 2; }));',
      options: ['[2, 4, 6]', '[undefined, undefined, undefined]', '[1, 2, 3]', 'A SyntaxError'],
      answer: 1, tags: 'arrays',
      explanation: 'The braces make it a block, and there is no return, so every callback returns undefined.' },
    { topic: 'Array Methods', type: 'fill_blank', difficulty: 'intermediate', points: 15,
      prompt: 'Complete the sum: [1,2,3].______((a, b) => a + b, 0)', answer: 'reduce', tags: 'arrays',
      explanation: 'reduce collapses an array to a single value, starting from the initial value you pass.' },
    { topic: 'Scope', type: 'multiple_choice', difficulty: 'intermediate', points: 15,
      prompt: 'What is block scope?',
      options: ['Variables live only inside their nearest curly braces', 'Variables live for the whole file', 'Variables live only inside functions', 'Variables can never be reassigned'],
      answer: 0, tags: 'scope',
      explanation: 'let and const are block-scoped; var is function-scoped.' },
    { topic: 'Closures', type: 'output', difficulty: 'advanced', points: 20,
      prompt: 'What does this print?',
      code: 'function counter() {\n  let count = 0;\n  return () => ++count;\n}\nconst next = counter();\nnext();\nconsole.log(next());',
      options: ['1', '2', 'undefined', 'ReferenceError'], answer: 1, tags: 'closures',
      explanation: 'The returned function closes over count, which survives between calls. Two calls give 2.' },
    { topic: 'Promises', type: 'multiple_choice', difficulty: 'intermediate', points: 15,
      prompt: 'What are the three states of a promise?',
      options: ['start, middle, end', 'pending, fulfilled, rejected', 'open, closed, failed', 'waiting, done, error'],
      answer: 1, tags: 'async',
      explanation: 'A promise is pending until it settles, either fulfilled with a value or rejected with a reason.' },
    { topic: 'Async/Await', type: 'multiple_choice', difficulty: 'intermediate', points: 15,
      prompt: 'Where may the await keyword be used?',
      options: ['Anywhere', 'Only inside an async function or a module top level', 'Only inside a loop', 'Only in the browser'],
      answer: 1, tags: 'async',
      explanation: 'Using await elsewhere is a SyntaxError. Inside modules, top-level await is also allowed.' },
    { topic: 'Async/Await', type: 'scenario', difficulty: 'advanced', points: 20,
      prompt: 'An async call sometimes fails and crashes your app with an unhandled rejection. What should you add?',
      options: ['A try/catch around the await', 'A longer timeout', 'More awaits', 'A while loop that retries forever'],
      answer: 0, tags: 'async',
      explanation: 'await throws on rejection, so try/catch (or .catch() on the promise) is what handles the failure.' },
    { topic: 'Fetch API', type: 'multiple_choice', difficulty: 'intermediate', points: 15,
      prompt: 'What does fetch() return?',
      options: ['The response body', 'A promise that resolves to a Response object', 'A string', 'JSON'],
      answer: 1, tags: 'async',
      explanation: 'You then call await response.json() to read and parse the body — a second promise.' },
    { topic: 'Fetch API', type: 'true_false', difficulty: 'advanced', points: 20,
      prompt: 'fetch() rejects its promise when the server responds with a 404.', answer: 'false', tags: 'async',
      explanation: 'fetch only rejects on network failure. Check response.ok yourself for HTTP error statuses.' },
    { topic: 'JSON', type: 'multiple_choice', difficulty: 'beginner', points: 10,
      prompt: 'Which method turns a JavaScript object into a JSON string?',
      options: ['JSON.parse()', 'JSON.stringify()', 'JSON.toString()', 'Object.toJSON()'],
      answer: 1, tags: 'json',
      explanation: 'stringify goes object to text; parse goes text to object.' },
    { topic: 'DOM', type: 'multiple_choice', difficulty: 'beginner', points: 10,
      prompt: 'Which method finds the first element matching a CSS selector?',
      options: ['document.getElement()', 'document.querySelector()', 'document.find()', 'document.select()'],
      answer: 1, tags: 'dom',
      explanation: 'querySelector takes any CSS selector and returns the first match, or null.' },
    { topic: 'DOM', type: 'scenario', difficulty: 'advanced', points: 20,
      prompt: 'You insert text a user typed using innerHTML. What is the risk?',
      options: ['It is slower', 'They can inject HTML and scripts into your page', 'The text loses its formatting', 'There is no risk'],
      answer: 1, tags: 'security',
      explanation: 'That is a cross-site scripting (XSS) hole. textContent inserts the same characters as plain text.' },
    { topic: 'Events', type: 'debug', difficulty: 'intermediate', points: 15,
      prompt: 'Why does this handler run immediately and then never again?',
      code: 'button.addEventListener("click", handleClick());',
      options: ['handleClick is not defined', 'The parentheses call the function and pass its return value', 'click is the wrong event name', 'addEventListener needs three arguments'],
      answer: 1, tags: 'events',
      explanation: 'Pass the function itself: addEventListener("click", handleClick).' },
    { topic: 'Events', type: 'multiple_choice', difficulty: 'intermediate', points: 15,
      prompt: 'What does event.preventDefault() do in a form submit handler?',
      options: ['Clears the form', 'Stops the browser reloading the page', 'Cancels the event listener', 'Validates the fields'],
      answer: 1, tags: 'events',
      explanation: 'It suppresses the browser’s built-in behaviour, which for a form is navigating to the action URL.' },
    { topic: 'Local Storage', type: 'multiple_choice', difficulty: 'intermediate', points: 15,
      prompt: 'What type of value can localStorage hold?',
      options: ['Any JavaScript value', 'Strings only', 'Numbers only', 'Objects only'],
      answer: 1, tags: 'storage',
      explanation: 'Everything is stored as a string, so objects go through JSON.stringify on the way in and JSON.parse on the way out.' },
    { topic: 'Error Handling', type: 'multiple_choice', difficulty: 'intermediate', points: 15,
      prompt: 'Which block always runs, whether or not an error was thrown?',
      options: ['try', 'catch', 'finally', 'throw'], answer: 2, tags: 'errors',
      explanation: 'finally is where you clean up — close a connection, hide a spinner, re-enable a button.' },
    { topic: 'Classes', type: 'multiple_choice', difficulty: 'intermediate', points: 15,
      prompt: 'Which method runs automatically when you write new Thing()?',
      options: ['init()', 'constructor()', 'create()', 'start()'], answer: 1, tags: 'classes',
      explanation: 'constructor receives the arguments passed to new and sets up the instance.' },
    { topic: 'Modules', type: 'multiple_choice', difficulty: 'intermediate', points: 15,
      prompt: 'How many default exports may one module have?',
      options: ['None', 'One', 'As many as you like', 'One per function'], answer: 1, tags: 'modules',
      explanation: 'A module can have at most one default export, plus any number of named exports.' },
    { topic: 'ES6+', type: 'output', difficulty: 'intermediate', points: 15,
      prompt: 'What is logged?',
      code: 'const user = { name: "Ada", age: 36 };\nconst { name } = user;\nconsole.log(name);',
      options: ['undefined', '"Ada"', '{ name: "Ada" }', 'An error'], answer: 1, tags: 'destructuring',
      explanation: 'Destructuring pulls the named property straight out into a variable of the same name.' },
    { topic: 'Math', type: 'output', difficulty: 'beginner', points: 10,
      prompt: 'What does Math.round(4.5) return?',
      code: 'console.log(Math.round(4.5));',
      options: ['4', '5', '4.5', 'NaN'], answer: 1, tags: 'math',
      explanation: 'Math.round goes to the nearest integer, with exact halves rounding up.' },
    { topic: 'Advanced JavaScript', type: 'scenario', difficulty: 'advanced', points: 20,
      prompt: 'A search box fires a request on every keystroke and floods your server. What technique fixes it?',
      options: ['Debouncing the input handler', 'Using a faster server', 'Removing the event listener', 'Switching to innerHTML'],
      answer: 0, tags: 'patterns',
      explanation: 'Debouncing waits until typing pauses before firing, so one request is sent instead of a dozen.' }
  ]
};
