// ==========================================================
// Coding Hub starter content - Python.
// ==========================================================

export default {
  subject: 'python',

  lessons: [
    {
      topic: 'Introduction',
      title: 'Your first Python program',
      summary: 'Run Python, print something, read input, and understand why indentation matters so much.',
      minutes: 12,
      objectives: [
        'Run a Python file from the terminal',
        'Use print() and input()',
        'Explain what indentation does in Python',
        'Write a comment'
      ],
      blocks: [
        { type: 'paragraph', text: 'Python is designed to be read. Where other languages use braces and semicolons, Python uses plain indentation, which means well-written Python looks a lot like the description of what it does.' },
        { type: 'code', language: 'python', code: 'print("Hello, world!")' },
        { type: 'paragraph', text: 'Save that as hello.py and run it with `python hello.py` (or `python3 hello.py` on macOS and Linux). That is the whole program — no class, no main function, no boilerplate.' },
        { type: 'heading', text: 'Talking to the user' },
        { type: 'code', language: 'python', code: 'name = input("What is your name? ")\nprint("Hello, " + name + "!")\nprint(f"Nice to meet you, {name}.")   # f-string — usually the neatest way' },
        { type: 'warning', title: 'input() always gives you text', text: 'Even if the user types 42, you get the string "42". Adding 1 to it raises a TypeError. Convert it first with int() or float().' },
        { type: 'code', language: 'python', code: 'age = int(input("How old are you? "))\nprint(f"Next year you will be {age + 1}.")' },
        { type: 'heading', text: 'Indentation is the syntax' },
        { type: 'paragraph', text: 'A block of code is defined by how far it is indented. Get this wrong and the program either does the wrong thing or refuses to run at all.' },
        { type: 'code', language: 'python', code: 'temperature = 30\n\nif temperature > 25:\n    print("It is warm")      # indented — inside the if\n    print("Have some water") # indented — also inside the if\nprint("Done")                # not indented — always runs' },
        { type: 'list', items: [
          'Use four spaces per level. Every Python style guide agrees on this.',
          'Never mix tabs and spaces in one file — Python will reject it.',
          'A line ending in a colon is always followed by an indented block.'
        ] },
        { type: 'heading', text: 'Comments' },
        { type: 'code', language: 'python', code: '# A single-line comment\n\ndef area(width, height):\n    """A docstring: explains what the function does."""\n    return width * height' },
        { type: 'heading', text: 'Common mistakes' },
        { type: 'list', items: [
          'Forgetting the colon at the end of an if, for or def line.',
          'Mixing tabs and spaces, which produces a TabError.',
          'Trying to do maths on the result of input() without converting it.',
          'Using print() where you meant return inside a function.'
        ] },
        { type: 'heading', text: 'Summary' },
        { type: 'list', items: [
          'print() writes out, input() reads in, and input always returns a string.',
          'f-strings are the clearest way to build text from values.',
          'Indentation defines blocks — four spaces, consistently.',
          '# starts a comment; a docstring documents a function.'
        ] }
      ],
      challenge: {
        title: 'A friendly greeter',
        description: 'Write a short program that asks for a name and a birth year, then greets the user and tells them their age.',
        requirements: [
          'Ask for a name and a birth year',
          'Convert the year to a number',
          'Print one greeting using an f-string',
          'If the year is in the future, print a polite message instead of a negative age'
        ],
        starterCode: 'name = input("What is your name? ")\nyear = input("Which year were you born? ")\n\n# convert, check and print here',
        expectedResult: 'For "Ada" and 2010 the program prints something like: "Hello Ada, you are about 16 this year." A future year gets a friendly message instead.',
        hints: [
          'int(year) converts the text to a whole number.',
          'You will need one if/else to catch the future year.'
        ],
        difficulty: 'beginner',
        points: 20
      }
    },

    {
      topic: 'Lists',
      title: 'Lists: Python’s everyday container',
      summary: 'Store many values in order, change them, slice them and loop over them.',
      minutes: 15,
      objectives: [
        'Create, read and change a list',
        'Use append, insert, remove, pop and sort',
        'Slice a list, including with negative indexes',
        'Loop over a list with and without its index'
      ],
      blocks: [
        { type: 'paragraph', text: 'A list holds an ordered collection of values. It can hold anything, including a mixture of types, and it can be changed after it is created.' },
        { type: 'code', language: 'python', code: 'scores = [45, 82, 67, 91]\nnames  = ["Ada", "Alan", "Grace"]\nmixed  = [1, "two", 3.0, True]\n\nprint(scores[0])    # 45   — first item\nprint(scores[-1])   # 91   — last item\nprint(len(scores))  # 4' },
        { type: 'heading', text: 'Changing a list' },
        { type: 'code', language: 'python', code: 'names.append("Linus")       # add to the end\nnames.insert(0, "Barbara")  # add at a position\nnames.remove("Alan")        # remove by value\nlast = names.pop()          # remove and return the last item\nnames.sort()                # sort in place\nnames.reverse()             # reverse in place' },
        { type: 'note', title: 'sort() vs sorted()', text: 'names.sort() changes the list and returns None. sorted(names) leaves the original alone and hands back a new list. Writing `names = names.sort()` is a classic bug — it sets names to None.' },
        { type: 'heading', text: 'Slicing' },
        { type: 'code', language: 'python', code: 'letters = ["a", "b", "c", "d", "e"]\n\nprint(letters[1:3])   # ["b", "c"]   — from 1 up to (not including) 3\nprint(letters[:2])    # ["a", "b"]\nprint(letters[2:])    # ["c", "d", "e"]\nprint(letters[-2:])   # ["d", "e"]\nprint(letters[::-1])  # ["e", "d", "c", "b", "a"] — reversed copy' },
        { type: 'heading', text: 'Looping' },
        { type: 'code', language: 'python', code: 'for name in names:\n    print(name)\n\nfor index, name in enumerate(names, start=1):\n    print(f"{index}. {name}")' },
        { type: 'paragraph', text: 'Reach for enumerate() rather than `for i in range(len(names))`. It is shorter and it is what an experienced Python developer expects to read.' },
        { type: 'heading', text: 'List comprehensions' },
        { type: 'code', language: 'python', code: 'squares = [n * n for n in range(1, 6)]        # [1, 4, 9, 16, 25]\npasses  = [s for s in scores if s >= 50]      # [82, 67, 91]' },
        { type: 'heading', text: 'Common mistakes' },
        { type: 'list', items: [
          'Assigning the result of .sort(), .append() or .reverse() — they all return None.',
          'Removing items from a list while looping over it, which skips entries.',
          'Copying with `b = a`, which gives two names for one list. Use a.copy() or a[:].',
          'Using a list where a set (unique items) or a dictionary (key to value) fits better.'
        ] },
        { type: 'heading', text: 'Summary' },
        { type: 'list', items: [
          'Lists are ordered, changeable and zero-indexed; -1 is the last item.',
          'append, insert, remove, pop and sort change the list in place.',
          'Slicing [start:stop] excludes the stop index and returns a new list.',
          'enumerate() gives you the index and the value together.'
        ] }
      ],
      challenge: {
        title: 'Marks report',
        description: 'Given a list of marks, produce a small report without using any library beyond built-ins.',
        requirements: [
          'Print the highest and lowest mark',
          'Print the average to one decimal place',
          'Print how many marks are 50 or above, using a list comprehension',
          'Print the marks sorted from highest to lowest, leaving the original list unchanged'
        ],
        starterCode: 'marks = [45, 82, 67, 91, 38, 55]\n\n# your report here',
        expectedResult: 'Highest 91, lowest 38, average 63.0, four passes, and a sorted copy [91, 82, 67, 55, 45, 38] with marks itself untouched.',
        hints: [
          'max(), min(), sum() and len() are all built in.',
          'sorted(marks, reverse=True) returns a new list.'
        ],
        difficulty: 'beginner',
        points: 30
      }
    },

    {
      topic: 'Functions',
      title: 'Functions and how Python passes arguments',
      summary: 'Define functions, use default and keyword arguments, and return more than one value.',
      minutes: 15,
      objectives: [
        'Define a function with def and return a value',
        'Use default, positional and keyword arguments',
        'Return several values as a tuple',
        'Avoid the mutable default argument trap'
      ],
      blocks: [
        { type: 'code', language: 'python', code: 'def add(a, b):\n    return a + b\n\nprint(add(2, 3))   # 5' },
        { type: 'paragraph', text: 'def names the function, the parentheses list the parameters, and the indented block is the body. A function with no return statement gives back None.' },
        { type: 'heading', text: 'Default and keyword arguments' },
        { type: 'code', language: 'python', code: 'def greet(name, greeting="Hello", excited=False):\n    mark = "!" if excited else "."\n    return f"{greeting}, {name}{mark}"\n\ngreet("Sam")                       # "Hello, Sam."\ngreet("Sam", "Welcome")            # "Welcome, Sam."\ngreet("Sam", excited=True)         # "Hello, Sam!"' },
        { type: 'paragraph', text: 'Keyword arguments let you skip over defaults and make the call site far easier to read. Parameters with defaults must come after those without.' },
        { type: 'heading', text: 'Returning several values' },
        { type: 'code', language: 'python', code: 'def stats(numbers):\n    return min(numbers), max(numbers), sum(numbers) / len(numbers)\n\nlowest, highest, average = stats([4, 8, 15, 16])\nprint(highest)   # 16' },
        { type: 'paragraph', text: 'Python packs the values into a tuple and unpacks them again on the receiving side.' },
        { type: 'heading', text: 'The mutable default trap' },
        { type: 'warning', title: 'This one bites everybody once', text: 'A default value is created once, when the function is defined — not each time it is called. A mutable default such as [] is therefore shared between every call.' },
        { type: 'code', language: 'python', code: '# Wrong\ndef add_item(item, basket=[]):\n    basket.append(item)\n    return basket\n\nadd_item("apple")   # ["apple"]\nadd_item("bread")   # ["apple", "bread"]  <- the same list!\n\n# Right\ndef add_item(item, basket=None):\n    if basket is None:\n        basket = []\n    basket.append(item)\n    return basket' },
        { type: 'heading', text: '*args and **kwargs' },
        { type: 'code', language: 'python', code: 'def total(*numbers):\n    return sum(numbers)\n\ntotal(1, 2, 3)        # 6\n\ndef describe(**details):\n    for key, value in details.items():\n        print(f"{key}: {value}")\n\ndescribe(name="Ada", age=36)' },
        { type: 'heading', text: 'Common mistakes' },
        { type: 'list', items: [
          'Printing instead of returning, so the caller gets None.',
          'A mutable default argument shared across calls.',
          'Putting a parameter with a default before one without — that is a SyntaxError.',
          'Forgetting the colon after the def line.'
        ] },
        { type: 'heading', text: 'Summary' },
        { type: 'list', items: [
          'def name(params): then an indented body.',
          'Defaults and keyword arguments make calls readable.',
          'Returning several values gives you a tuple you can unpack.',
          'Never use a list or dict as a default value — use None.'
        ] }
      ],
      challenge: {
        title: 'A reusable price calculator',
        description: 'Write a function that works out a final price from a list of item prices.',
        requirements: [
          'total_price(prices, tax=0.2, discount=0) returns the final amount',
          'The discount is a fraction applied before tax',
          'The result is rounded to two decimal places',
          'An empty list returns 0.0, not an error',
          'Calling total_price([100], discount=0.1) returns 108.0'
        ],
        starterCode: 'def total_price(prices, tax=0.2, discount=0):\n    # your code here\n    pass\n\nprint(total_price([100]))                 # 120.0\nprint(total_price([100], discount=0.1))   # 108.0\nprint(total_price([]))                    # 0.0',
        expectedResult: 'The three calls print 120.0, 108.0 and 0.0.',
        hints: [
          'sum(prices) gives the subtotal; guard the empty list first.',
          'Apply the discount, then the tax, then round().'
        ],
        difficulty: 'intermediate',
        points: 35
      }
    }
  ],

  questions: [
    { topic: 'Introduction', type: 'multiple_choice', difficulty: 'beginner', points: 10,
      prompt: 'Which function displays output in Python?',
      options: ['echo()', 'print()', 'console.log()', 'write()'], answer: 1, tags: 'basics',
      explanation: 'print() writes to standard output; console.log() is JavaScript.' },
    { topic: 'Introduction', type: 'multiple_choice', difficulty: 'beginner', points: 10,
      prompt: 'How does Python know where a block of code starts and ends?',
      options: ['Curly braces', 'Indentation', 'Semicolons', 'The begin and end keywords'],
      answer: 1, tags: 'syntax',
      explanation: 'Indentation is part of Python’s grammar, not just a style choice. Four spaces per level is the standard.' },
    { topic: 'Introduction', type: 'debug', difficulty: 'beginner', points: 15,
      prompt: 'What is wrong with this code?',
      code: 'if score > 50\n    print("Pass")',
      options: ['print needs brackets', 'The if line is missing a colon', 'score must be a string', 'Nothing is wrong'],
      answer: 1, tags: 'syntax',
      explanation: 'Every line that opens a block — if, for, while, def, class — ends with a colon.' },
    { topic: 'Introduction', type: 'output', difficulty: 'intermediate', points: 15,
      prompt: 'What happens when the user types 5?',
      code: 'age = input("Age? ")\nprint(age + 1)',
      options: ['Prints 6', 'Prints 51', 'Raises a TypeError', 'Prints 5'], answer: 2, tags: 'input',
      explanation: 'input() returns a string, and you cannot add an int to a str. Convert with int(age) first.' },
    { topic: 'Variables', type: 'multiple_choice', difficulty: 'beginner', points: 10,
      prompt: 'Which variable name is valid in Python?',
      options: ['2names', 'my-name', 'my_name', 'class'], answer: 2, tags: 'variables',
      explanation: 'Names cannot start with a digit, cannot contain a hyphen, and cannot be a reserved keyword such as class.' },
    { topic: 'Data Types', type: 'output', difficulty: 'beginner', points: 10,
      prompt: 'What does this print?',
      code: 'print(type(3.0))',
      options: ["<class 'int'>", "<class 'float'>", "<class 'number'>", "<class 'decimal'>"],
      answer: 1, tags: 'types',
      explanation: 'The decimal point makes it a float, even though the value is a whole number.' },
    { topic: 'Data Types', type: 'output', difficulty: 'intermediate', points: 15,
      prompt: 'What is the result?',
      code: 'print(7 // 2, 7 % 2, 7 / 2)',
      options: ['3 1 3.5', '3.5 1 3.5', '3 3.5 1', '3 1 3'], answer: 0, tags: 'operators',
      explanation: '// is integer division, % is the remainder, and / always gives a float.' },
    { topic: 'Strings', type: 'multiple_choice', difficulty: 'beginner', points: 10,
      prompt: 'What is an f-string?',
      options: ['A string that must be a filename', 'A string with an f prefix that can embed expressions in braces', 'A faster string type', 'A formatted file'],
      answer: 1, tags: 'strings',
      explanation: 'f"Hello {name}" evaluates whatever is inside the braces and inserts the result.' },
    { topic: 'Strings', type: 'output', difficulty: 'intermediate', points: 15,
      prompt: 'What is printed?',
      code: 'word = "Python"\nprint(word[1:4])',
      options: ['"Pyt"', '"yth"', '"ytho"', '"tho"'], answer: 1, tags: 'strings',
      explanation: 'Slicing starts at index 1 and stops before index 4, giving characters 1, 2 and 3.' },
    { topic: 'Strings', type: 'true_false', difficulty: 'intermediate', points: 15,
      prompt: 'Python strings can be changed in place, for example word[0] = "J".', answer: 'false', tags: 'strings',
      explanation: 'Strings are immutable. Build a new one instead: "J" + word[1:].' },
    { topic: 'Lists', type: 'multiple_choice', difficulty: 'beginner', points: 10,
      prompt: 'Which method adds an item to the end of a list?',
      options: ['add()', 'append()', 'push()', 'insert()'], answer: 1, tags: 'lists',
      explanation: 'append() adds one item at the end; insert(index, item) puts it at a chosen position.' },
    { topic: 'Lists', type: 'output', difficulty: 'intermediate', points: 15,
      prompt: 'What is printed?',
      code: 'items = [1, 2, 3]\nresult = items.sort()\nprint(result)',
      options: ['[1, 2, 3]', 'None', '[3, 2, 1]', 'An error'], answer: 1, tags: 'lists',
      explanation: 'sort() sorts in place and returns None. Use sorted(items) if you want a new list back.' },
    { topic: 'Lists', type: 'output', difficulty: 'intermediate', points: 15,
      prompt: 'What is printed?',
      code: 'letters = ["a", "b", "c", "d"]\nprint(letters[-2:])',
      options: ["['c', 'd']", "['a', 'b']", "['b', 'c']", "['d']"], answer: 0, tags: 'lists',
      explanation: '-2 counts back from the end, and an empty stop means "to the end".' },
    { topic: 'Tuples', type: 'multiple_choice', difficulty: 'intermediate', points: 15,
      prompt: 'What is the main difference between a list and a tuple?',
      options: ['Tuples are faster to print', 'Tuples cannot be changed after creation', 'Tuples can only hold numbers', 'There is no difference'],
      answer: 1, tags: 'types',
      explanation: 'Tuples are immutable, which makes them usable as dictionary keys and safe to share.' },
    { topic: 'Sets', type: 'output', difficulty: 'intermediate', points: 15,
      prompt: 'What is printed?',
      code: 'print(len({1, 2, 2, 3, 3, 3}))',
      options: ['6', '3', '1', 'An error'], answer: 1, tags: 'types',
      explanation: 'A set stores only unique values, so the duplicates collapse to {1, 2, 3}.' },
    { topic: 'Dictionaries', type: 'multiple_choice', difficulty: 'beginner', points: 10,
      prompt: 'How do you read the value for the key "name" from a dict called user?',
      options: ['user.name', 'user["name"]', 'user->name', 'user(name)'], answer: 1, tags: 'dicts',
      explanation: 'Square brackets with the key; user.get("name") returns None instead of raising KeyError when it is missing.' },
    { topic: 'Dictionaries', type: 'scenario', difficulty: 'intermediate', points: 15,
      prompt: 'Reading user["age"] raises KeyError but you want a default of 0 instead. What do you use?',
      options: ['user.get("age", 0)', 'user["age"] or 0', 'default(user, "age")', 'try user.age'],
      answer: 0, tags: 'dicts',
      explanation: '.get() takes an optional fallback and never raises.' },
    { topic: 'Conditions', type: 'output', difficulty: 'beginner', points: 10,
      prompt: 'What is printed?',
      code: 'x = 10\nif x > 5:\n    print("big")\nelif x > 8:\n    print("bigger")\nelse:\n    print("small")',
      options: ['big', 'bigger', 'small', 'big and bigger'], answer: 0, tags: 'conditions',
      explanation: 'Only the first matching branch runs; elif is never reached once the if is true.' },
    { topic: 'Loops', type: 'output', difficulty: 'beginner', points: 10,
      prompt: 'What does this print?',
      code: 'for i in range(3):\n    print(i)',
      options: ['1 2 3', '0 1 2', '0 1 2 3', '3'], answer: 1, tags: 'loops',
      explanation: 'range(3) produces 0, 1, 2 — it starts at 0 and stops before 3.' },
    { topic: 'Loops', type: 'fill_blank', difficulty: 'intermediate', points: 15,
      prompt: 'Complete the loop that gives both index and value: for i, name in _________(names):', answer: 'enumerate', tags: 'loops',
      explanation: 'enumerate() yields (index, value) pairs and accepts a start argument.' },
    { topic: 'Functions', type: 'multiple_choice', difficulty: 'beginner', points: 10,
      prompt: 'Which keyword defines a function?',
      options: ['function', 'def', 'fun', 'define'], answer: 1, tags: 'functions',
      explanation: 'def name(parameters): followed by an indented body.' },
    { topic: 'Functions', type: 'output', difficulty: 'intermediate', points: 15,
      prompt: 'What is printed?',
      code: 'def double(n):\n    print(n * 2)\n\nresult = double(4)\nprint(result)',
      options: ['8 then 8', '8 then None', 'None then 8', '8 only'], answer: 1, tags: 'functions',
      explanation: 'The function prints 8 but has no return, so result is None.' },
    { topic: 'Functions', type: 'debug', difficulty: 'advanced', points: 20,
      prompt: 'Why does the second call return ["apple", "bread"]?',
      code: 'def add_item(item, basket=[]):\n    basket.append(item)\n    return basket\n\nadd_item("apple")\nadd_item("bread")',
      options: ['A bug in Python', 'The default list is created once and shared between calls', 'append always merges lists', 'basket is a global variable'],
      answer: 1, tags: 'functions',
      explanation: 'Default values are evaluated once at definition time. Use basket=None and create the list inside.' },
    { topic: 'Parameters', type: 'true_false', difficulty: 'intermediate', points: 15,
      prompt: 'A parameter with a default value may appear before one without a default.', answer: 'false', tags: 'functions',
      explanation: 'That is a SyntaxError — defaults must come last.' },
    { topic: 'Modules', type: 'multiple_choice', difficulty: 'beginner', points: 10,
      prompt: 'How do you use the sqrt function from the math module?',
      options: ['import math then math.sqrt(9)', 'use math.sqrt(9)', 'include math; sqrt(9)', 'require("math").sqrt(9)'],
      answer: 0, tags: 'modules',
      explanation: 'Or `from math import sqrt` to bring just that one name into scope.' },
    { topic: 'File Handling', type: 'multiple_choice', difficulty: 'intermediate', points: 15,
      prompt: 'Why is `with open("data.txt") as f:` preferred?',
      options: ['It is faster', 'It closes the file automatically, even if an error occurs', 'It allows writing', 'It is the only way to read a file'],
      answer: 1, tags: 'files',
      explanation: 'The with block is a context manager: the file is closed when the block ends, however it ends.' },
    { topic: 'Exceptions', type: 'multiple_choice', difficulty: 'intermediate', points: 15,
      prompt: 'Which block handles an error that was raised?',
      options: ['try', 'except', 'finally', 'raise'], answer: 1, tags: 'errors',
      explanation: 'try holds the risky code, except handles the failure, finally always runs afterwards.' },
    { topic: 'Exceptions', type: 'scenario', difficulty: 'advanced', points: 20,
      prompt: 'Why is a bare `except:` discouraged?',
      options: ['It is slower', 'It catches everything, including typing mistakes and Ctrl+C', 'It only works in Python 2', 'It cannot be nested'],
      answer: 1, tags: 'errors',
      explanation: 'Catching everything hides real bugs. Catch the specific exceptions you expect, such as ValueError.' },
    { topic: 'Classes', type: 'multiple_choice', difficulty: 'intermediate', points: 15,
      prompt: 'What is the first parameter of an instance method conventionally called?',
      options: ['this', 'self', 'me', 'cls'], answer: 1, tags: 'classes',
      explanation: 'self refers to the instance. cls is the convention for class methods.' },
    { topic: 'Classes', type: 'fill_blank', difficulty: 'intermediate', points: 15,
      prompt: 'Complete the constructor name: def ______(self, name):', answer: '__init__', tags: 'classes',
      explanation: '__init__ runs automatically when an instance is created.' },
    { topic: 'Inheritance', type: 'multiple_choice', difficulty: 'advanced', points: 20,
      prompt: 'Which call runs the parent class’s version of a method?',
      options: ['parent()', 'super()', 'base()', 'self.parent()'], answer: 1, tags: 'classes',
      explanation: 'super().__init__(...) is the usual way to run the parent constructor from a subclass.' },
    { topic: 'List Comprehension', type: 'output', difficulty: 'intermediate', points: 15,
      prompt: 'What is printed?',
      code: 'print([n * n for n in range(1, 4)])',
      options: ['[1, 2, 3]', '[1, 4, 9]', '[2, 4, 6]', '[1, 4, 9, 16]'], answer: 1, tags: 'comprehensions',
      explanation: 'range(1, 4) gives 1, 2, 3, and each is squared.' },
    { topic: 'List Comprehension', type: 'fill_blank', difficulty: 'advanced', points: 20,
      prompt: 'Complete the comprehension that keeps only even numbers: [n for n in nums ____ n % 2 == 0]', answer: 'if', tags: 'comprehensions',
      explanation: 'The optional if clause filters items before they reach the output list.' },
    { topic: 'Lambda Functions', type: 'multiple_choice', difficulty: 'advanced', points: 20,
      prompt: 'What is a lambda?',
      options: ['A module', 'A small anonymous function written on one line', 'A loop type', 'A kind of class'],
      answer: 1, tags: 'functions',
      explanation: 'lambda x: x * 2 is a nameless function, most often passed to sorted(), map() or filter().' },
    { topic: 'Decorators', type: 'multiple_choice', difficulty: 'advanced', points: 20,
      prompt: 'What does the @ syntax above a function do?',
      options: ['Adds a comment', 'Wraps the function in another function', 'Marks it as private', 'Runs it immediately'],
      answer: 1, tags: 'advanced',
      explanation: 'A decorator takes the function, wraps it and rebinds the name — used for logging, timing and access checks.' },
    { topic: 'Generators', type: 'multiple_choice', difficulty: 'advanced', points: 20,
      prompt: 'Which keyword makes a function a generator?',
      options: ['return', 'yield', 'async', 'generate'], answer: 1, tags: 'advanced',
      explanation: 'yield produces a value and pauses, so the values are computed one at a time instead of all at once.' },
    { topic: 'JSON', type: 'multiple_choice', difficulty: 'intermediate', points: 15,
      prompt: 'Which function turns a JSON string into a Python dictionary?',
      options: ['json.dumps()', 'json.loads()', 'json.parse()', 'json.read()'], answer: 1, tags: 'json',
      explanation: 'loads = load string. dumps = dump string (the other direction).' },
    { topic: 'Virtual Environments', type: 'scenario', difficulty: 'advanced', points: 20,
      prompt: 'Two projects need different versions of the same library. What solves this?',
      options: ['Installing both globally', 'A virtual environment per project', 'Renaming one of the libraries', 'Using Python 2 for one of them'],
      answer: 1, tags: 'tooling',
      explanation: 'python -m venv .venv creates an isolated set of packages for that project alone.' },
    { topic: 'Advanced Python', type: 'output', difficulty: 'advanced', points: 20,
      prompt: 'What is printed?',
      code: 'a = [1, 2, 3]\nb = a\nb.append(4)\nprint(len(a))',
      options: ['3', '4', '0', 'An error'], answer: 1, tags: 'references',
      explanation: 'b = a makes a second name for the same list. Use a.copy() or list(a) for a real copy.' }
  ]
};
