// ==========================================================
// Coding Hub starter content - React.
// ==========================================================

export default {
  subject: 'react',

  lessons: [
    {
      topic: 'Components',
      title: 'Components and props',
      summary: 'Build an interface from small reusable functions, and pass data into them.',
      minutes: 15,
      objectives: [
        'Write a function component',
        'Pass and read props',
        'Render a list with a key',
        'Compose small components into a bigger one'
      ],
      blocks: [
        { type: 'paragraph', text: 'A React component is a JavaScript function that returns markup. That is the whole idea: your interface becomes a tree of small functions, each responsible for one piece.' },
        { type: 'code', language: 'javascript', code: 'function Greeting() {\n  return <h1>Hello!</h1>;\n}\n\n// Use it like an element\n<Greeting />' },
        { type: 'warning', title: 'Capital letters matter', text: '<Greeting /> renders your component. <greeting /> renders an unknown HTML tag. React uses the capital letter to tell the two apart.' },
        { type: 'heading', text: 'Props: passing data in' },
        { type: 'code', language: 'javascript', code: 'function Greeting({ name, excited = false }) {\n  return <h1>Hello, {name}{excited ? "!" : "."}</h1>;\n}\n\n<Greeting name="Ada" excited />\n<Greeting name="Alan" />' },
        { type: 'paragraph', text: 'Props arrive as a single object, which is almost always destructured in the parameter list. Anything in braces inside JSX is a JavaScript expression — a variable, a call, a ternary.' },
        { type: 'note', title: 'Props are read-only', text: 'A component must never change its own props. If a value needs to change, it belongs in state, owned by whichever component is responsible for it.' },
        { type: 'heading', text: 'children' },
        { type: 'code', language: 'javascript', code: 'function Card({ title, children }) {\n  return (\n    <section className="card">\n      <h2>{title}</h2>\n      {children}\n    </section>\n  );\n}\n\n<Card title="Progress">\n  <p>You have finished 12 lessons.</p>\n</Card>' },
        { type: 'heading', text: 'Rendering a list' },
        { type: 'code', language: 'javascript', code: 'function LessonList({ lessons }) {\n  return (\n    <ul>\n      {lessons.map(lesson => (\n        <li key={lesson.id}>{lesson.title}</li>\n      ))}\n    </ul>\n  );\n}' },
        { type: 'paragraph', text: 'The key must be a stable, unique id from your data. Using the array index breaks as soon as items are added, removed or reordered, because React then matches the wrong element to the wrong data.' },
        { type: 'heading', text: 'JSX rules worth memorising' },
        { type: 'list', items: [
          'class becomes className, and for becomes htmlFor.',
          'Every tag must close: <img />, <br />.',
          'A component returns exactly one root element — wrap siblings in a fragment <>…</>.',
          'Attribute names are camelCase: onClick, tabIndex, maxLength.'
        ] },
        { type: 'heading', text: 'Common mistakes' },
        { type: 'list', items: [
          'Lowercase component names, which render as unknown HTML tags.',
          'Forgetting key, or using the array index as one.',
          'Returning two sibling elements with no wrapper.',
          'Trying to modify props inside the component.'
        ] },
        { type: 'heading', text: 'Summary' },
        { type: 'list', items: [
          'A component is a function returning JSX, named with a capital letter.',
          'Props pass data down and are read-only.',
          'children lets a component wrap arbitrary content.',
          'Lists need a stable key from your data.'
        ] }
      ],
      challenge: {
        title: 'A reusable lesson card',
        description: 'Build a LessonCard component and render a list of them.',
        requirements: [
          'LessonCard takes title, minutes and done as props',
          'When done is true the card shows a tick, otherwise it shows the minutes',
          'A LessonList component maps over an array and renders one card each',
          'Each card has a key taken from the lesson id, not the index'
        ],
        starterCode: 'const lessons = [\n  { id: 1, title: "What HTML is", minutes: 12, done: true },\n  { id: 2, title: "Selectors",     minutes: 15, done: false }\n];\n\nfunction LessonCard(/* props */) {\n  // your code here\n}\n\nfunction LessonList({ lessons }) {\n  // your code here\n}',
        expectedResult: 'Two cards render: the first showing a completed tick, the second showing "15 min", with no key warning in the console.',
        hints: [
          'Destructure the props in the parameter list.',
          'A ternary inside braces chooses between the tick and the minutes.'
        ],
        difficulty: 'intermediate',
        points: 35
      }
    },

    {
      topic: 'useState',
      title: 'useState: giving a component memory',
      summary: 'Store values that change, update them correctly, and understand why the screen re-renders.',
      minutes: 16,
      objectives: [
        'Add state to a component with useState',
        'Update state without mutating it',
        'Use the updater function when the new value depends on the old one',
        'Lift state up to a shared parent'
      ],
      blocks: [
        { type: 'paragraph', text: 'Props come from outside and cannot change. State belongs to the component and can. When state changes, React runs the component again and updates the screen.' },
        { type: 'code', language: 'javascript', code: 'import { useState } from "react";\n\nfunction Counter() {\n  const [count, setCount] = useState(0);\n\n  return (\n    <button onClick={() => setCount(count + 1)}>\n      Clicked {count} times\n    </button>\n  );\n}' },
        { type: 'paragraph', text: 'useState returns a pair: the current value, and a function to change it. The argument is the starting value, used only on the first render.' },
        { type: 'warning', title: 'Never assign to state directly', text: 'count = count + 1 does nothing useful — React does not know anything changed, so nothing re-renders. Always go through the setter.' },
        { type: 'heading', text: 'When the new value depends on the old one' },
        { type: 'code', language: 'javascript', code: '// Risky: both calls read the same stale count\nsetCount(count + 1);\nsetCount(count + 1);   // ends up +1, not +2\n\n// Safe: each call receives the latest value\nsetCount(c => c + 1);\nsetCount(c => c + 1);  // +2' },
        { type: 'heading', text: 'Objects and arrays in state' },
        { type: 'paragraph', text: 'React compares the old and new value by identity. Changing an array in place leaves it the same object, so React sees no change. Always create a new one.' },
        { type: 'code', language: 'javascript', code: 'const [tasks, setTasks] = useState([]);\n\n// Wrong — same array, no re-render\ntasks.push(newTask);\nsetTasks(tasks);\n\n// Right — a new array\nsetTasks([...tasks, newTask]);\nsetTasks(tasks.filter(t => t.id !== id));\nsetTasks(tasks.map(t => (t.id === id ? { ...t, done: true } : t)));' },
        { type: 'heading', text: 'A controlled input' },
        { type: 'code', language: 'javascript', code: 'function SearchBox() {\n  const [term, setTerm] = useState("");\n\n  return (\n    <input\n      value={term}\n      onChange={event => setTerm(event.target.value)}\n      placeholder="Search lessons"\n    />\n  );\n}' },
        { type: 'heading', text: 'Lifting state up' },
        { type: 'paragraph', text: 'When two components need the same value, move the state into their closest common parent and pass the value down as a prop, plus a function to change it. This is the single most useful structural idea in React.' },
        { type: 'heading', text: 'Rules of hooks' },
        { type: 'list', items: [
          'Only call hooks at the top level of a component — never inside an if, a loop or a nested function.',
          'Only call hooks from React components or from your own custom hooks.',
          'The order of hook calls must be identical on every render, which is why the first rule exists.'
        ] },
        { type: 'heading', text: 'Common mistakes' },
        { type: 'list', items: [
          'Mutating an array or object in state instead of replacing it.',
          'Expecting the state variable to change on the very next line — it updates on the next render.',
          'Calling useState inside a condition.',
          'Writing onClick={handleClick()} instead of onClick={handleClick}, which runs it immediately.'
        ] },
        { type: 'heading', text: 'Summary' },
        { type: 'list', items: [
          'const [value, setValue] = useState(initial).',
          'Setting state schedules a re-render; assigning does nothing.',
          'Use the updater form when the new value depends on the old.',
          'Replace arrays and objects rather than mutating them.'
        ] }
      ],
      challenge: {
        title: 'A working to-do component',
        description: 'Build a to-do list in React with add, toggle and delete.',
        requirements: [
          'A controlled input adds a task on submit and then clears',
          'Clicking a task toggles it between done and not done',
          'A delete button removes a task',
          'The tasks array is never mutated — every update creates a new array',
          'A counter shows how many tasks are still outstanding'
        ],
        starterCode: 'import { useState } from "react";\n\nexport default function TodoList() {\n  const [tasks, setTasks] = useState([]);\n  const [draft, setDraft] = useState("");\n\n  // your handlers here\n\n  return (\n    <div>\n      {/* form, list and counter here */}\n    </div>\n  );\n}',
        expectedResult: 'Tasks can be added, ticked off and removed, the input clears after each add, and the outstanding count stays correct.',
        hints: [
          'Add with [...tasks, newTask], toggle with map, delete with filter.',
          'Give each task an id — Date.now() is good enough here.'
        ],
        difficulty: 'advanced',
        points: 45
      }
    }
  ],

  questions: [
    { topic: 'React Introduction', type: 'multiple_choice', difficulty: 'beginner', points: 10,
      prompt: 'What is React?',
      options: ['A programming language', 'A JavaScript library for building user interfaces', 'A database', 'A CSS framework'],
      answer: 1, tags: 'basics',
      explanation: 'React is a library focused on the view layer. Routing, data fetching and state management come from other packages.' },
    { topic: 'React Introduction', type: 'true_false', difficulty: 'intermediate', points: 15,
      prompt: 'React updates the real DOM directly for every state change.', answer: 'false', tags: 'basics',
      explanation: 'React works out the smallest set of real DOM changes needed and applies only those.' },
    { topic: 'Components', type: 'multiple_choice', difficulty: 'beginner', points: 10,
      prompt: 'Why must a component name start with a capital letter?',
      options: ['It is only a style convention', 'Lowercase names are treated as HTML tags', 'JavaScript requires it', 'It makes it render faster'],
      answer: 1, tags: 'components',
      explanation: 'JSX uses the capital letter to decide between your component and a built-in element.' },
    { topic: 'Components', type: 'debug', difficulty: 'intermediate', points: 15,
      prompt: 'Why does this component fail to compile?',
      code: 'function Profile() {\n  return (\n    <h1>Ada</h1>\n    <p>Engineer</p>\n  );\n}',
      options: ['p cannot follow h1', 'A component must return one root element', 'The function needs props', 'JSX needs quotes'],
      answer: 1, tags: 'jsx',
      explanation: 'Wrap the siblings in a fragment: <>…</>.' },
    { topic: 'JSX', type: 'multiple_choice', difficulty: 'beginner', points: 10,
      prompt: 'Which attribute sets a CSS class in JSX?',
      options: ['class', 'className', 'cssClass', 'styleName'], answer: 1, tags: 'jsx',
      explanation: 'class is a reserved word in JavaScript, so JSX uses className (and htmlFor instead of for).' },
    { topic: 'JSX', type: 'output', difficulty: 'intermediate', points: 15,
      prompt: 'What renders?',
      code: 'const name = "Ada";\n<h1>Hello {name.toUpperCase()}</h1>',
      options: ['Hello {name.toUpperCase()}', 'Hello ADA', 'Hello Ada', 'An error'], answer: 1, tags: 'jsx',
      explanation: 'Braces hold any JavaScript expression, and the result is inserted.' },
    { topic: 'Props', type: 'true_false', difficulty: 'beginner', points: 10,
      prompt: 'A component may change the props it receives.', answer: 'false', tags: 'props',
      explanation: 'Props are read-only. A value that must change belongs in state, owned by a parent.' },
    { topic: 'Props', type: 'multiple_choice', difficulty: 'intermediate', points: 15,
      prompt: 'What does the children prop contain?',
      options: ['Nested components inside the tags', 'Every child component in the app', 'The component’s state', 'An array of ids'],
      answer: 0, tags: 'props',
      explanation: 'Whatever you put between <Card> and </Card> arrives as children.' },
    { topic: 'State', type: 'multiple_choice', difficulty: 'beginner', points: 10,
      prompt: 'What is the difference between props and state?',
      options: ['None', 'Props come from the parent and are read-only; state is owned by the component and can change', 'State is faster', 'Props are only for text'],
      answer: 1, tags: 'state',
      explanation: 'Data flows down as props; the component that owns a changing value holds it in state.' },
    { topic: 'useState', type: 'multiple_choice', difficulty: 'beginner', points: 10,
      prompt: 'What does useState return?',
      options: ['The current value only', 'An array of the current value and a setter function', 'A promise', 'An object with get and set'],
      answer: 1, tags: 'hooks',
      explanation: 'It is destructured as const [value, setValue] = useState(initial).' },
    { topic: 'useState', type: 'debug', difficulty: 'intermediate', points: 15,
      prompt: 'Why does the screen never update?',
      code: 'const [count, setCount] = useState(0);\n\nfunction handleClick() {\n  count = count + 1;\n}',
      options: ['count needs to be let', 'State must be changed through setCount', 'useState needs an argument', 'handleClick needs to be async'],
      answer: 1, tags: 'hooks',
      explanation: 'Assigning directly does not tell React anything changed. Call setCount(c => c + 1).' },
    { topic: 'useState', type: 'output', difficulty: 'advanced', points: 20,
      prompt: 'Starting from 0, what is count after this handler runs once?',
      code: 'setCount(count + 1);\nsetCount(count + 1);',
      options: ['0', '1', '2', '3'], answer: 1, tags: 'hooks',
      explanation: 'Both calls read the same stale count. setCount(c => c + 1) twice would give 2.' },
    { topic: 'useEffect', type: 'multiple_choice', difficulty: 'intermediate', points: 15,
      prompt: 'What does an empty dependency array mean in useEffect(fn, [])?',
      options: ['The effect runs after every render', 'The effect runs once after the first render', 'The effect never runs', 'The effect runs before rendering'],
      answer: 1, tags: 'hooks',
      explanation: 'With no dependencies there is nothing to change, so it runs once on mount (twice in development Strict Mode).' },
    { topic: 'useEffect', type: 'scenario', difficulty: 'advanced', points: 20,
      prompt: 'An effect starts an interval. What should it return?',
      options: ['The interval id', 'A cleanup function that clears the interval', 'true', 'Nothing'],
      answer: 1, tags: 'hooks',
      explanation: 'Without cleanup the interval keeps running after the component unmounts, which leaks memory and causes warnings.' },
    { topic: 'useRef', type: 'multiple_choice', difficulty: 'advanced', points: 20,
      prompt: 'What happens when you change a ref’s .current value?',
      options: ['The component re-renders', 'Nothing re-renders', 'React throws an error', 'All children re-render'],
      answer: 1, tags: 'hooks',
      explanation: 'Refs are for values that should survive renders without causing one — DOM nodes, timers, previous values.' },
    { topic: 'Events', type: 'debug', difficulty: 'intermediate', points: 15,
      prompt: 'Why does this run immediately on render instead of on click?',
      code: '<button onClick={handleClick()}>Save</button>',
      options: ['handleClick is not defined', 'The parentheses call the function during render', 'onClick should be onclick', 'Buttons need a type'],
      answer: 1, tags: 'events',
      explanation: 'Pass the function itself: onClick={handleClick}, or wrap it: onClick={() => handleClick(id)}.' },
    { topic: 'Lists', type: 'multiple_choice', difficulty: 'intermediate', points: 15,
      prompt: 'Why should a list key not be the array index?',
      options: ['It is slower', 'It breaks when items are added, removed or reordered', 'Indexes are not unique', 'React forbids numbers'],
      answer: 1, tags: 'lists',
      explanation: 'React matches elements to data by key. If the key shifts with position, state ends up attached to the wrong row.' },
    { topic: 'Conditional Rendering', type: 'multiple_choice', difficulty: 'intermediate', points: 15,
      prompt: 'Which pattern renders an element only when isLoggedIn is true?',
      options: ['{isLoggedIn && <Dashboard />}', '{if (isLoggedIn) <Dashboard />}', '{isLoggedIn ? <Dashboard />}', '<Dashboard if={isLoggedIn} />'],
      answer: 0, tags: 'jsx',
      explanation: 'JSX holds expressions, not statements, so && or a ternary is used instead of if.' },
    { topic: 'Forms', type: 'multiple_choice', difficulty: 'intermediate', points: 15,
      prompt: 'What makes an input "controlled"?',
      options: ['It has a name attribute', 'Its value comes from state and it has an onChange handler', 'It is inside a form', 'It is required'],
      answer: 1, tags: 'forms',
      explanation: 'React state becomes the single source of truth for what the field contains.' },
    { topic: 'Hooks', type: 'multiple_choice', difficulty: 'intermediate', points: 15,
      prompt: 'Where may a hook be called?',
      options: ['Anywhere', 'Only at the top level of a component or custom hook', 'Only inside useEffect', 'Only in class components'],
      answer: 1, tags: 'hooks',
      explanation: 'React tracks hooks by call order, so that order must be identical on every render.' },
    { topic: 'Context', type: 'scenario', difficulty: 'advanced', points: 20,
      prompt: 'A theme value is being passed down through five layers of components that do not use it. What fixes this?',
      options: ['More props', 'Context', 'useRef', 'A global variable'], answer: 1, tags: 'context',
      explanation: 'Context lets any descendant read a value directly, avoiding "prop drilling" through components that do not care.' },
    { topic: 'API Requests', type: 'multiple_choice', difficulty: 'advanced', points: 20,
      prompt: 'Where should a fetch for initial data usually go?',
      options: ['Directly in the component body', 'Inside useEffect', 'Inside the return statement', 'In the props'],
      answer: 1, tags: 'data',
      explanation: 'The component body runs on every render, so fetching there causes an endless loop of requests.' },
    { topic: 'Performance', type: 'multiple_choice', difficulty: 'advanced', points: 20,
      prompt: 'What does useMemo do?',
      options: ['Stores state', 'Caches an expensive calculation between renders', 'Fetches data', 'Replaces useEffect'],
      answer: 1, tags: 'performance',
      explanation: 'It recomputes only when its dependencies change. Measure before reaching for it — most calculations are cheap.' },
    { topic: 'Advanced React', type: 'scenario', difficulty: 'advanced', points: 20,
      prompt: 'Two sibling components need the same piece of changing data. What is the standard solution?',
      options: ['Duplicate the state in both', 'Lift the state up to their closest common parent', 'Use a global variable', 'Use useRef in both'],
      answer: 1, tags: 'patterns',
      explanation: 'One owner passes the value down as a prop, plus a setter, so the two can never disagree.' }
  ]
};
